"""Shared skill catalog used by both the resume extractor
(parsers/extractors/skills.py) and the JD parser (parsers/job_description_parser.py).

Previously these two files each kept their own independent, differently-shaped skill
list — they drifted apart (JD's list was smaller and missing entries the resume list
had, and vice versa), which silently hurt matching quality: a skill the resume extractor
recognized but the JD extractor didn't (or the reverse) could never show up as MATCHED
even when it was genuinely present in both documents. One shared list, one place to
extend.

Originally biased almost entirely toward this project's own web/mobile stack (React,
NestJS, Prisma, Tailwind...) — expanded 2026-07-28 to cover DevOps/infra, security,
networking, operating systems, data/ML, broader cloud/database/testing, and other
professional fields, since the narrow original list caused CVs/JDs outside web dev
(e.g. DevOps, security) to match on only a handful of terms.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class SkillDefinition:
    name: str
    normalized_name: str
    aliases: tuple[str, ...]
    category: str


SKILL_CATALOG: tuple[SkillDefinition, ...] = (
    # --- Languages ---
    SkillDefinition("Python", "python", ("python",), "language"),
    SkillDefinition("JavaScript", "javascript", ("javascript", "js"), "language"),
    SkillDefinition("TypeScript", "typescript", ("typescript", "ts"), "language"),
    SkillDefinition("Java", "java", ("java",), "language"),
    SkillDefinition("C#", "csharp", ("c#", "c sharp"), "language"),
    SkillDefinition("PHP", "php", ("php",), "language"),
    SkillDefinition("Ruby", "ruby", ("ruby",), "language"),
    SkillDefinition("C", "c", ("c",), "language"),
    SkillDefinition("C++", "cpp", ("c++",), "language"),
    SkillDefinition("Go", "go", ("go", "golang"), "language"),
    SkillDefinition("Rust", "rust", ("rust",), "language"),
    SkillDefinition("Kotlin", "kotlin", ("kotlin",), "language"),
    SkillDefinition("Swift", "swift", ("swift",), "language"),
    SkillDefinition("Scala", "scala", ("scala",), "language"),
    SkillDefinition("Dart", "dart", ("dart",), "language"),
    SkillDefinition("R", "r_lang", ("r language", "r programming"), "language"),
    SkillDefinition("MATLAB", "matlab", ("matlab",), "language"),
    SkillDefinition("Bash", "bash", ("bash", "bash scripting", "shell script", "shell scripting"), "scripting"),
    SkillDefinition("PowerShell", "powershell", ("powershell",), "scripting"),
    SkillDefinition("SQL", "sql", ("sql",), "database"),
    # --- Frontend / Mobile ---
    SkillDefinition("HTML", "html", ("html",), "frontend"),
    SkillDefinition("CSS", "css", ("css",), "frontend"),
    SkillDefinition("Bootstrap", "bootstrap", ("bootstrap",), "frontend"),
    SkillDefinition("React", "react", ("react", "reactjs", "react.js"), "frontend"),
    SkillDefinition("React Native", "react_native", ("react native",), "mobile"),
    SkillDefinition("Expo", "expo", ("expo",), "mobile"),
    SkillDefinition("Vite", "vite", ("vite",), "frontend"),
    SkillDefinition("Next.js", "nextjs", ("next.js", "nextjs"), "frontend"),
    SkillDefinition("Vue", "vue", ("vue", "vue.js", "vuejs"), "frontend"),
    SkillDefinition("Angular", "angular", ("angular",), "frontend"),
    SkillDefinition("Tailwind CSS", "tailwind_css", ("tailwind css", "tailwind"), "frontend"),
    SkillDefinition("shadcn/ui", "shadcn_ui", ("shadcn/ui", "shadcn ui", "shadcn"), "frontend"),
    SkillDefinition("Zustand", "zustand", ("zustand",), "frontend"),
    SkillDefinition("Redux Toolkit", "redux_toolkit", ("redux toolkit", "rtk"), "frontend"),
    SkillDefinition("TanStack Query", "tanstack_query", ("tanstack query", "react query"), "frontend"),
    SkillDefinition("React Context", "react_context", ("react context", "context api"), "frontend"),
    SkillDefinition("Flutter", "flutter", ("flutter",), "mobile"),
    SkillDefinition("BLoC/Cubit", "bloc_cubit", ("bloc/cubit", "bloc", "cubit"), "mobile"),
    SkillDefinition("Dio", "dio", ("dio",), "mobile"),
    SkillDefinition("SwiftUI", "swiftui", ("swiftui",), "mobile"),
    SkillDefinition("Jetpack Compose", "jetpack_compose", ("jetpack compose",), "mobile"),
    SkillDefinition("Xcode", "xcode", ("xcode",), "mobile"),
    SkillDefinition("Android Studio", "android_studio", ("android studio",), "mobile"),
    # --- Backend ---
    SkillDefinition("Node.js", "nodejs", ("node.js", "nodejs", "node"), "backend"),
    SkillDefinition("ASP.NET", "aspnet", ("asp.net", "asp net"), "backend"),
    SkillDefinition("ASP.NET MVC", "aspnet_mvc", ("asp.net mvc", "asp net mvc"), "backend"),
    SkillDefinition("NestJS", "nestjs", ("nestjs", "nest.js"), "backend"),
    SkillDefinition("Express", "express", ("express", "express.js"), "backend"),
    SkillDefinition("Socket.IO", "socket_io", ("socket.io", "socket io"), "backend"),
    SkillDefinition("RBAC", "rbac", ("rbac", "role based access control", "role-based access control"), "backend"),
    SkillDefinition("JWT", "jwt", ("jwt", "json web token", "json web tokens"), "backend"),
    SkillDefinition("FastAPI", "fastapi", ("fastapi", "fast api"), "backend"),
    SkillDefinition("Django", "django", ("django",), "backend"),
    SkillDefinition("Flask", "flask", ("flask",), "backend"),
    SkillDefinition("Laravel", "laravel", ("laravel",), "backend"),
    SkillDefinition("Spring Boot", "spring_boot", ("spring boot", "springboot"), "backend"),
    SkillDefinition(".NET", "dotnet", (".net", "dotnet"), "backend"),
    SkillDefinition("REST API", "rest_api", ("rest api", "rest apis", "restful api", "rest"), "backend"),
    SkillDefinition("GraphQL", "graphql", ("graphql", "graph ql"), "backend"),
    # --- Databases ---
    SkillDefinition("PostgreSQL", "postgresql", ("postgresql", "postgres", "postgre sql"), "database"),
    SkillDefinition("MySQL", "mysql", ("mysql",), "database"),
    SkillDefinition("SQL Server", "sql_server", ("sql server", "mssql"), "database"),
    SkillDefinition("Oracle Database", "oracle_db", ("oracle database", "oracle db"), "database"),
    SkillDefinition("SQLite", "sqlite", ("sqlite",), "database"),
    SkillDefinition("MongoDB", "mongodb", ("mongodb", "mongo db"), "database"),
    SkillDefinition("Mongoose", "mongoose", ("mongoose",), "orm"),
    SkillDefinition("Redis", "redis", ("redis",), "database"),
    SkillDefinition("Cassandra", "cassandra", ("cassandra",), "database"),
    SkillDefinition("DynamoDB", "dynamodb", ("dynamodb",), "database"),
    SkillDefinition("Elasticsearch", "elasticsearch", ("elasticsearch", "elastic search"), "database"),
    SkillDefinition("Neo4j", "neo4j", ("neo4j",), "database"),
    SkillDefinition("Prisma", "prisma", ("prisma",), "orm"),
    # --- Cloud / Platform ---
    SkillDefinition("AWS", "aws", ("aws", "amazon web services"), "cloud"),
    SkillDefinition("AWS EC2", "aws_ec2", ("aws ec2", "ec2"), "cloud"),
    SkillDefinition("AWS Lambda", "aws_lambda", ("aws lambda", "lambda"), "cloud"),
    SkillDefinition("Amazon S3", "amazon_s3", ("amazon s3", "aws s3", "s3"), "cloud"),
    SkillDefinition("CloudFormation", "cloudformation", ("cloudformation",), "cloud"),
    SkillDefinition("Azure", "azure", ("azure", "microsoft azure"), "cloud"),
    SkillDefinition("Azure DevOps", "azure_devops", ("azure devops",), "devops"),
    SkillDefinition("GCP", "gcp", ("gcp", "google cloud", "google cloud platform"), "cloud"),
    SkillDefinition("DigitalOcean", "digitalocean", ("digitalocean", "digital ocean"), "cloud"),
    SkillDefinition("Heroku", "heroku", ("heroku",), "cloud"),
    SkillDefinition("Cloudflare", "cloudflare", ("cloudflare",), "cloud"),
    SkillDefinition("Firebase", "firebase", ("firebase",), "cloud"),
    SkillDefinition("Supabase", "supabase", ("supabase",), "cloud"),
    SkillDefinition("Supabase Storage", "supabase_storage", ("supabase storage",), "cloud"),
    SkillDefinition("Cloudinary", "cloudinary", ("cloudinary",), "cloud"),
    SkillDefinition("Vercel", "vercel", ("vercel",), "cloud"),
    SkillDefinition("Render", "render", ("render",), "cloud"),
    SkillDefinition("Object Storage (S3/R2/MinIO)", "object_storage", ("minio", "cloudflare r2", "object storage"), "cloud"),
    # --- DevOps / Infra ---
    SkillDefinition("Docker", "docker", ("docker",), "devops"),
    SkillDefinition("Kubernetes", "kubernetes", ("kubernetes", "k8s"), "devops"),
    SkillDefinition("Helm", "helm", ("helm",), "devops"),
    SkillDefinition("ArgoCD", "argocd", ("argocd", "argo cd"), "devops"),
    SkillDefinition("Terraform", "terraform", ("terraform",), "devops"),
    SkillDefinition("Ansible", "ansible", ("ansible",), "devops"),
    SkillDefinition("Pulumi", "pulumi", ("pulumi",), "devops"),
    SkillDefinition("Puppet", "puppet", ("puppet",), "devops"),
    SkillDefinition("Chef", "chef", ("chef",), "devops"),
    SkillDefinition("Vagrant", "vagrant", ("vagrant",), "devops"),
    SkillDefinition("Packer", "packer", ("packer",), "devops"),
    SkillDefinition("CI/CD", "ci_cd", ("ci/cd", "cicd", "continuous integration"), "devops"),
    SkillDefinition("GitHub Actions", "github_actions", ("github actions", "gh actions"), "devops"),
    SkillDefinition("GitLab CI", "gitlab_ci", ("gitlab ci",), "devops"),
    SkillDefinition("Jenkins", "jenkins", ("jenkins",), "devops"),
    SkillDefinition("Nginx", "nginx", ("nginx",), "devops"),
    SkillDefinition("HAProxy", "haproxy", ("haproxy",), "devops"),
    SkillDefinition("Prometheus", "prometheus", ("prometheus",), "devops"),
    SkillDefinition("Grafana", "grafana", ("grafana",), "devops"),
    SkillDefinition("ELK Stack", "elk_stack", ("elk stack", "elk"), "devops"),
    SkillDefinition("Loki", "loki", ("loki",), "devops"),
    SkillDefinition("Datadog", "datadog", ("datadog",), "devops"),
    SkillDefinition("Splunk", "splunk", ("splunk",), "devops"),
    SkillDefinition("New Relic", "new_relic", ("new relic",), "devops"),
    SkillDefinition("Istio", "istio", ("istio",), "devops"),
    SkillDefinition("Linkerd", "linkerd", ("linkerd",), "devops"),
    SkillDefinition("Consul", "consul", ("consul",), "devops"),
    SkillDefinition("HashiCorp Vault", "hashicorp_vault", ("hashicorp vault", "vault"), "devops"),
    SkillDefinition("Kafka", "kafka", ("kafka",), "devops"),
    SkillDefinition("RabbitMQ", "rabbitmq", ("rabbitmq",), "devops"),
    SkillDefinition("OpenShift", "openshift", ("openshift",), "devops"),
    SkillDefinition("Rancher", "rancher", ("rancher",), "devops"),
    SkillDefinition("Nomad", "nomad", ("nomad",), "devops"),
    # --- Operating Systems ---
    SkillDefinition("Linux", "linux", ("linux",), "os"),
    SkillDefinition("Ubuntu", "ubuntu", ("ubuntu",), "os"),
    SkillDefinition("CentOS", "centos", ("centos",), "os"),
    SkillDefinition("RedHat", "redhat", ("redhat", "red hat", "rhel"), "os"),
    SkillDefinition("Debian", "debian", ("debian",), "os"),
    SkillDefinition("Windows Server", "windows_server", ("windows server",), "os"),
    # --- Networking ---
    SkillDefinition("TCP/IP", "tcp_ip", ("tcp/ip",), "networking"),
    SkillDefinition("DNS", "dns", ("dns",), "networking"),
    SkillDefinition("VLAN", "vlan", ("vlan",), "networking"),
    SkillDefinition("NAT", "nat", ("nat",), "networking"),
    SkillDefinition("BGP", "bgp", ("bgp",), "networking"),
    SkillDefinition("OSPF", "ospf", ("ospf",), "networking"),
    SkillDefinition("Load Balancer", "load_balancer", ("load balancer", "load balancing"), "networking"),
    SkillDefinition("Reverse Proxy", "reverse_proxy", ("reverse proxy",), "networking"),
    SkillDefinition("Firewall", "firewall", ("firewall",), "networking"),
    SkillDefinition("pfSense", "pfsense", ("pfsense",), "networking"),
    SkillDefinition("SSL/TLS", "ssl_tls", ("ssl/tls", "ssl", "tls"), "networking"),
    SkillDefinition("VPN", "vpn", ("vpn",), "networking"),
    SkillDefinition("Routing and Switching", "routing_switching", ("routing", "switching"), "networking"),
    # --- Security ---
    SkillDefinition("Wazuh", "wazuh", ("wazuh",), "security"),
    SkillDefinition("Coraza WAF", "coraza_waf", ("coraza waf", "coraza"), "security"),
    SkillDefinition("NeuVector", "neuvector", ("neuvector",), "security"),
    SkillDefinition("Kubescape", "kubescape", ("kubescape",), "security"),
    SkillDefinition("SIEM", "siem", ("siem",), "security"),
    SkillDefinition("IDS/IPS", "ids_ips", ("ids/ips", "ids", "ips", "intrusion detection", "intrusion prevention"), "security"),
    SkillDefinition("WAF", "waf", ("waf", "web application firewall"), "security"),
    SkillDefinition("Wireshark", "wireshark", ("wireshark",), "security"),
    SkillDefinition("Burp Suite", "burp_suite", ("burp suite", "burpsuite"), "security"),
    SkillDefinition("Nmap", "nmap", ("nmap",), "security"),
    SkillDefinition("Metasploit", "metasploit", ("metasploit",), "security"),
    SkillDefinition("OWASP ZAP", "owasp_zap", ("owasp zap", "zap"), "security"),
    SkillDefinition("Snyk", "snyk", ("snyk",), "security"),
    SkillDefinition("SonarQube", "sonarqube", ("sonarqube", "sonar qube"), "security"),
    SkillDefinition("Nessus", "nessus", ("nessus",), "security"),
    SkillDefinition("Vulnerability Assessment", "vulnerability_assessment", ("vulnerability assessment",), "security"),
    SkillDefinition("Penetration Testing", "penetration_testing", ("penetration testing", "pentest", "pentesting"), "security"),
    SkillDefinition("DevSecOps", "devsecops", ("devsecops",), "security"),
    # --- Data / ML ---
    SkillDefinition("Pandas", "pandas", ("pandas",), "data"),
    SkillDefinition("NumPy", "numpy", ("numpy",), "data"),
    SkillDefinition("Scikit-learn", "scikit_learn", ("scikit-learn", "scikit learn", "sklearn"), "ml"),
    SkillDefinition("TensorFlow", "tensorflow", ("tensorflow",), "ml"),
    SkillDefinition("PyTorch", "pytorch", ("pytorch",), "ml"),
    SkillDefinition("Keras", "keras", ("keras",), "ml"),
    SkillDefinition("Apache Spark", "apache_spark", ("apache spark", "spark"), "data"),
    SkillDefinition("Hadoop", "hadoop", ("hadoop",), "data"),
    SkillDefinition("Airflow", "airflow", ("airflow", "apache airflow"), "data"),
    SkillDefinition("dbt", "dbt", ("dbt",), "data"),
    SkillDefinition("Snowflake", "snowflake", ("snowflake",), "data"),
    SkillDefinition("BigQuery", "bigquery", ("bigquery", "big query"), "data"),
    SkillDefinition("Tableau", "tableau", ("tableau",), "data"),
    SkillDefinition("Power BI", "power_bi", ("power bi", "powerbi"), "data"),
    SkillDefinition("Looker", "looker", ("looker", "looker studio"), "data"),
    SkillDefinition("Jupyter", "jupyter", ("jupyter", "jupyter notebook"), "data"),
    SkillDefinition("Whisper AI", "whisper_ai", ("whisper ai", "openai whisper", "whisper"), "ai"),
    SkillDefinition("Gemini AI", "gemini_ai", ("gemini ai", "gemini"), "ai"),
    # --- Testing / QA ---
    SkillDefinition("Jest", "jest", ("jest",), "testing"),
    SkillDefinition("Pytest", "pytest", ("pytest",), "testing"),
    SkillDefinition("Selenium", "selenium", ("selenium",), "testing"),
    SkillDefinition("Cypress", "cypress", ("cypress",), "testing"),
    SkillDefinition("Playwright", "playwright", ("playwright",), "testing"),
    SkillDefinition("JUnit", "junit", ("junit",), "testing"),
    SkillDefinition("Postman", "postman", ("postman",), "testing"),
    SkillDefinition("JMeter", "jmeter", ("jmeter",), "testing"),
    # --- Tools / Collaboration ---
    SkillDefinition("Git", "git", ("git",), "tooling"),
    SkillDefinition("GitHub", "github", ("github",), "tooling"),
    SkillDefinition("GitLab", "gitlab", ("gitlab",), "tooling"),
    SkillDefinition("Bitbucket", "bitbucket", ("bitbucket",), "tooling"),
    SkillDefinition("Jira", "jira", ("jira",), "tooling"),
    SkillDefinition("Confluence", "confluence", ("confluence",), "tooling"),
    SkillDefinition("Trello", "trello", ("trello",), "tooling"),
    SkillDefinition("Notion", "notion", ("notion",), "tooling"),
    SkillDefinition("Slack", "slack", ("slack",), "tooling"),
    # --- Design ---
    SkillDefinition("Figma", "figma", ("figma",), "design"),
    SkillDefinition("Adobe XD", "adobe_xd", ("adobe xd",), "design"),
    SkillDefinition("Sketch", "sketch", ("sketch",), "design"),
    SkillDefinition("Photoshop", "photoshop", ("photoshop",), "design"),
    SkillDefinition("Illustrator", "illustrator", ("illustrator",), "design"),
    # --- Marketing / Sales ---
    SkillDefinition("Search Engine Optimization", "seo", ("seo", "search engine optimization", "search engine optimisation"), "marketing"),
    SkillDefinition("Search Engine Marketing", "sem", ("sem", "search engine marketing"), "marketing"),
    SkillDefinition("Content Marketing", "content_marketing", ("content marketing", "content strategy"), "marketing"),
    SkillDefinition("Email Marketing", "email_marketing", ("email marketing", "email campaigns"), "marketing"),
    SkillDefinition("Social Media Marketing", "social_media_marketing", ("social media marketing", "smm", "social media management"), "marketing"),
    SkillDefinition("Affiliate Marketing", "affiliate_marketing", ("affiliate marketing", "affiliate management"), "marketing"),
    SkillDefinition("Growth Hacking", "growth_hacking", ("growth hacking", "growth marketing"), "marketing"),
    SkillDefinition("Performance Marketing", "performance_marketing", ("performance marketing",), "marketing"),
    SkillDefinition("Inbound Marketing", "inbound_marketing", ("inbound marketing",), "marketing"),
    SkillDefinition("Conversion Rate Optimization", "conversion_rate_optimization", ("conversion rate optimization", "cro"), "marketing"),
    SkillDefinition("Account-Based Marketing", "account_based_marketing", ("account-based marketing", "abm"), "marketing"),
    SkillDefinition("Pay-Per-Click", "ppc", ("ppc", "pay-per-click", "pay per click"), "marketing"),
    SkillDefinition("Copywriting", "copywriting", ("copywriting", "copy writing"), "marketing"),
    SkillDefinition("Mailchimp", "mailchimp", ("mailchimp",), "marketing"),
    SkillDefinition("Klaviyo", "klaviyo", ("klaviyo",), "marketing"),
    SkillDefinition("Marketo", "marketo", ("marketo", "adobe marketo"), "marketing"),
    SkillDefinition("Pardot", "pardot", ("pardot", "marketing cloud account engagement"), "marketing"),
    SkillDefinition("ActiveCampaign", "activecampaign", ("activecampaign", "active campaign"), "marketing"),
    SkillDefinition("Brevo", "brevo", ("brevo", "sendinblue"), "marketing"),
    SkillDefinition("Constant Contact", "constant_contact", ("constant contact",), "marketing"),
    SkillDefinition("ConvertKit", "convertkit", ("convertkit", "kit"), "marketing"),
    SkillDefinition("Google Search Console", "google_search_console", ("google search console", "gsc"), "marketing"),
    SkillDefinition("Google Tag Manager", "google_tag_manager", ("google tag manager", "gtm"), "marketing"),
    SkillDefinition("Screaming Frog", "screaming_frog", ("screaming frog", "screaming frog seo spider"), "marketing"),
    SkillDefinition("Yoast SEO", "yoast_seo", ("yoast", "yoast seo"), "marketing"),
    SkillDefinition("Moz", "moz", ("moz", "moz pro"), "marketing"),
    SkillDefinition("BuzzSumo", "buzzsumo", ("buzzsumo",), "marketing"),
    SkillDefinition("Hootsuite", "hootsuite", ("hootsuite",), "marketing"),
    SkillDefinition("Sprout Social", "sprout_social", ("sprout social",), "marketing"),
    SkillDefinition("Buffer", "buffer", ("buffer",), "marketing"),
    SkillDefinition("Later", "later", ("later", "later.com"), "marketing"),
    SkillDefinition("TikTok Ads", "tiktok_ads", ("tiktok ads", "tiktok ads manager"), "marketing"),
    SkillDefinition("LinkedIn Ads", "linkedin_ads", ("linkedin ads", "linkedin campaign manager"), "marketing"),
    SkillDefinition("Twitter Ads", "twitter_ads", ("twitter ads", "x ads"), "marketing"),
    SkillDefinition("Pinterest Ads", "pinterest_ads", ("pinterest ads",), "marketing"),
    SkillDefinition("Criteo", "criteo", ("criteo",), "marketing"),
    SkillDefinition("The Trade Desk", "the_trade_desk", ("the trade desk", "ttd"), "marketing"),
    SkillDefinition("Mixpanel", "mixpanel", ("mixpanel",), "marketing"),
    SkillDefinition("Amplitude", "amplitude", ("amplitude", "amplitude analytics"), "marketing"),
    SkillDefinition("Hotjar", "hotjar", ("hotjar",), "marketing"),
    SkillDefinition("Crazy Egg", "crazy_egg", ("crazy egg",), "marketing"),
    SkillDefinition("Optimizely", "optimizely", ("optimizely",), "marketing"),
    SkillDefinition("VWO", "vwo", ("vwo", "visual website optimizer"), "marketing"),
    SkillDefinition("Lead Generation", "lead_generation", ("lead generation", "lead gen"), "sales"),
    SkillDefinition("Sales Prospecting", "sales_prospecting", ("sales prospecting", "prospecting"), "sales"),
    SkillDefinition("Cold Calling", "cold_calling", ("cold calling",), "sales"),
    SkillDefinition("Cold Emailing", "cold_emailing", ("cold emailing", "cold outreach"), "sales"),
    SkillDefinition("B2B Sales", "b2b_sales", ("b2b sales", "business to business sales"), "sales"),
    SkillDefinition("B2C Sales", "b2c_sales", ("b2c sales", "business to consumer sales"), "sales"),
    SkillDefinition("Enterprise Sales", "enterprise_sales", ("enterprise sales",), "sales"),
    SkillDefinition("SaaS Sales", "saas_sales", ("saas sales",), "sales"),
    SkillDefinition("Solution Selling", "solution_selling", ("solution selling",), "sales"),
    SkillDefinition("Consultative Selling", "consultative_selling", ("consultative selling",), "sales"),
    SkillDefinition("Sales Pipeline Management", "sales_pipeline_management", ("sales pipeline", "pipeline management"), "sales"),
    SkillDefinition("Key Account Management", "key_account_management", ("key account management", "kam", "account management"), "sales"),
    SkillDefinition("Customer Acquisition", "customer_acquisition", ("customer acquisition", "cac"), "sales"),
    SkillDefinition("Customer Retention", "customer_retention", ("customer retention", "churn reduction"), "sales"),
    SkillDefinition("Sales Operations", "sales_operations", ("sales operations", "sales ops"), "sales"),
    SkillDefinition("Sales Enablement", "sales_enablement", ("sales enablement",), "sales"),
    SkillDefinition("Contract Negotiation", "contract_negotiation", ("contract negotiation", "deal closing"), "sales"),
    SkillDefinition("Salesforce Sales Cloud", "salesforce_sales_cloud", ("salesforce sales cloud", "sales cloud"), "sales"),
    SkillDefinition("Pipedrive", "pipedrive", ("pipedrive",), "sales"),
    SkillDefinition("Zoho CRM", "zoho_crm", ("zoho crm", "zoho"), "sales"),
    SkillDefinition("Freshsales", "freshsales", ("freshsales", "freshworks crm"), "sales"),
    SkillDefinition("Dynamics 365 Sales", "dynamics_365_sales", ("dynamics 365 sales", "microsoft dynamics crm", "dynamics crm"), "sales"),
    SkillDefinition("Close CRM", "close_crm", ("close crm", "close.com"), "sales"),
    SkillDefinition("Outreach", "outreach_io", ("outreach", "outreach.io"), "sales"),
    SkillDefinition("Salesloft", "salesloft", ("salesloft",), "sales"),
    SkillDefinition("Gong", "gong", ("gong", "gong.io"), "sales"),
    SkillDefinition("Chorus.ai", "chorus_ai", ("chorus.ai", "chorus"), "sales"),
    SkillDefinition("Apollo.io", "apollo_io", ("apollo.io", "apollo io", "apollo"), "sales"),
    SkillDefinition("ZoomInfo", "zoominfo", ("zoominfo", "discoverorg"), "sales"),
    SkillDefinition("Lusha", "lusha", ("lusha",), "sales"),
    SkillDefinition("Clearbit", "clearbit", ("clearbit",), "sales"),
    SkillDefinition("Hunter.io", "hunter_io", ("hunter.io", "hunter io"), "sales"),
    SkillDefinition("LinkedIn Sales Navigator", "linkedin_sales_navigator", ("linkedin sales navigator", "sales navigator"), "sales"),
    SkillDefinition("Docusign", "docusign", ("docusign",), "sales"),
    SkillDefinition("PandaDoc", "pandadoc", ("pandadoc",), "sales"),
    SkillDefinition("Proposify", "proposify", ("proposify",), "sales"),
)
